language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - unzip
    - curl
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
env:
  - MONO_THREADS_PER_CPU=2000 MONO_MANAGED_WATCHER=disabled
mono:
  - 4.0.5
os:
  - linux
install:
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
  - source install.sh
script:
  - dnvm use default -runtime mono
  - docfx docfx.json